# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 18:59
from __future__ import unicode_literals

from django.db import migrations


def create_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    Site.objects.create(
        id=1,
        domain='schools.texastribune.org',
        name='Texas Public Schools Explorer')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site)
    ]
