services:
  web:
    environment:
      - DATABASE_URL
    depends_on:
      - db

  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
