SCHEMA = {
    'staff-and-student-information': {
        'all_students_count': 'PETALLC',
        'african_american_count': 'PETBLAC',
        'african_american_percent': 'PETBLAP',
        'american_indian_count': 'PETINDC',
        'american_indian_percent': 'PETINDP',
        'asian_count': 'PETASIC',
        'asian_percent': 'PETASIP',
        'hispanic_count': 'PETHISC',
        'hispanic_percent': 'PETHISP',
        'pacific_islander_count': 'PETPCIC',
        'pacific_islander_percent': 'PETPCIP',
        'two_or_more_races_count': 'PETTWOC',
        'two_or_more_races_percent': 'PETTWOP',
        'white_count': 'PETWHIC',
        'white_percent': 'PETWHIP',
        'early_childhood_education_count': 'PETGEEC',
        'early_childhood_education_percent': 'PETGEEP',
        'prek_count': 'PETGPKC',
        'prek_percent': 'PETGPKP',
        'kindergarten_count': 'PETGKNC',
        'kindergarten_percent': 'PETGKNP',
        'first_count': 'PETG01C',
        'first_percent': 'PETG01P',
        'second_count': 'PETG02C',
        'second_percent': 'PETG02P',
        'third_count': 'PETG03C',
        'third_percent': 'PETG03P',
        'fourth_count': 'PETG04C',
        'fourth_percent': 'PETG04P',
        'fifth_count': 'PETG05C',
        'fifth_percent': 'PETG05P',
        'sixth_count': 'PETG06C',
        'sixth_percent': 'PETG06P',
        'seventh_count': 'PETG07C',
        'seventh_percent': 'PETG07P',
        'eighth_count': 'PETG08C',
        'eighth_percent': 'PETG08P',
        'ninth_count': 'PETG09C',
        'ninth_percent': 'PETG09P',
        'tenth_count': 'PETG10C',
        'tenth_percent': 'PETG10P',
        'eleventh_count': 'PETG11C',
        'eleventh_percent': 'PETG11P',
        'twelfth_count': 'PETG12C',
        'twelfth_percent': 'PETG12P',
        'at_risk_count': 'PETRSKC',
        'at_risk_percent': 'PETRSKP',
        'economically_disadvantaged_count': 'PETECOC',
        'economically_disadvantaged_percent': 'PETECOP',
        'limited_english_proficient_count': 'PETLEPC',
        'limited_english_proficient_percent': 'PETLEPP',
        'bilingual_esl_count': 'PETBILC',
        'bilingual_esl_percent': 'PETBILP',
        'career_technical_education_count': 'PETVOCC',
        'career_technical_education_percent': 'PETVOCP',
        'gifted_and_talented_count': 'PETGIFC',
        'gifted_and_talented_percent': 'PETGIFP',
        'special_education_count': 'PETSPEC',
        'special_education_percent': 'PETSPEP',
        'class_size_avg_kindergarten': 'PCTGKGA',
        'class_size_avg_first': 'PCTG01A',
        'class_size_avg_second': 'PCTG02A',
        'class_size_avg_third': 'PCTG03A',
        'class_size_avg_fourth': 'PCTG04A',
        'class_size_avg_fifth': 'PCTG05A',
        'class_size_avg_sixth': 'PCTG06A',
        'class_size_avg_mixed_elementary': 'PCTGMEA',
        'class_size_avg_secondary_english': 'PCTENGA',
        'class_size_avg_secondary_foreign_language': 'PCTFLAA',
        'class_size_avg_secondary_math': 'PCTMATA',
        'class_size_avg_secondary_science': 'PCTSCIA',
        'class_size_avg_secondary_social_studies': 'PCTSOCA',
        'students_per_teacher': 'PSTKIDR',
        'teacher_avg_tenure': 'PSTTENA',
        'teacher_avg_experience': 'PSTEXPA',
        'teacher_avg_base_salary': 'PSTTOSA',
        'teacher_avg_beginning_salary': 'PST00SA',
        'teacher_avg_1_to_5_year_salary': 'PST01SA',
        'teacher_avg_6_to_10_year_salary': 'PST06SA',
        'teacher_avg_11_to_20_year_salary': 'PST11SA',
        'teacher_avg_20_plus_year_salary': 'PST20SA',
    },
    'postsecondary-readiness-and-non-staar-performance-indicators': {
        # 'college_ready_graduates_english_all_students_count': 'ACRR',
        'college_ready_graduates_english_all_students_percent': 'ACRR',
        # 'college_ready_graduates_english_african_american_count': 'BCRR',
        'college_ready_graduates_english_african_american_percent': 'BCRR',
        # 'college_ready_graduates_english_american_indian_count': 'ICRR',
        'college_ready_graduates_english_american_indian_percent': 'ICRR',
        # 'college_ready_graduates_english_asian_count': '3CRR',
        'college_ready_graduates_english_asian_percent': '3CRR',
        # 'college_ready_graduates_english_hispanic_count': 'HCRR',
        'college_ready_graduates_english_hispanic_percent': 'HCRR',
        # 'college_ready_graduates_english_pacific_islander_count': '4CRR',
        'college_ready_graduates_english_pacific_islander_percent': '4CRR',
        # 'college_ready_graduates_english_two_or_more_races_count': '2CRR',
        'college_ready_graduates_english_two_or_more_races_percent': '2CRR',
        # 'college_ready_graduates_english_white_count': 'WCRR',
        'college_ready_graduates_english_white_percent': 'WCRR',
        # 'college_ready_graduates_english_economically_disadvantaged_count': 'ECRR',
        'college_ready_graduates_english_economically_disadvantaged_percent': 'ECRR',
        # 'college_ready_graduates_english_limited_english_proficient_count': 'LCRR',
        'college_ready_graduates_english_limited_english_proficient_percent': 'LCRR',
        # 'college_ready_graduates_english_at_risk_count': 'RCRR',
        'college_ready_graduates_english_at_risk_percent': 'RCRR',
        # 'college_ready_graduates_math_all_students_count': 'ACRM',
        'college_ready_graduates_math_all_students_percent': 'ACRM',
        # 'college_ready_graduates_math_african_american_count': 'BCRM',
        'college_ready_graduates_math_african_american_percent': 'BCRM',
        # 'college_ready_graduates_math_american_indian_count': 'ICRM',
        'college_ready_graduates_math_american_indian_percent': 'ICRM',
        # 'college_ready_graduates_math_asian_count': '3CRM',
        'college_ready_graduates_math_asian_percent': '3CRM',
        # 'college_ready_graduates_math_hispanic_count': 'HCRM',
        'college_ready_graduates_math_hispanic_percent': 'HCRM',
        # 'college_ready_graduates_math_pacific_islander_count': '4CRM',
        'college_ready_graduates_math_pacific_islander_percent': '4CRM',
        # 'college_ready_graduates_math_two_or_more_races_count': '2CRM',
        'college_ready_graduates_math_two_or_more_races_percent': '2CRM',
        # 'college_ready_graduates_math_white_count': 'WCRM',
        'college_ready_graduates_math_white_percent': 'WCRM',
        # 'college_ready_graduates_math_economically_disadvantaged_count': 'ECRM',
        'college_ready_graduates_math_economically_disadvantaged_percent': 'ECRM',
        # 'college_ready_graduates_math_limited_english_proficient_count': 'LCRM',
        'college_ready_graduates_math_limited_english_proficient_percent': 'LCRM',
        # 'college_ready_graduates_math_at_risk_count': 'RCRM',
        'college_ready_graduates_math_at_risk_percent': 'RCRM',
        # 'college_ready_graduates_both_all_students_count': 'ACRB',
        'college_ready_graduates_both_all_students_percent': 'ACRB',
        # 'college_ready_graduates_both_african_american_count': 'BCRB',
        'college_ready_graduates_both_african_american_percent': 'BCRB',
        # 'college_ready_graduates_both_asian_count': '3CRB',
        'college_ready_graduates_both_asian_percent': '3CRB',
        # 'college_ready_graduates_both_hispanic_count': 'HCRB',
        'college_ready_graduates_both_hispanic_percent': 'HCRB',
        # 'college_ready_graduates_both_american_indian_count': 'ICRB',
        'college_ready_graduates_both_american_indian_percent': 'ICRB',
        # 'college_ready_graduates_both_pacific_islander_count': '4CRB',
        'college_ready_graduates_both_pacific_islander_percent': '4CRB',
        # 'college_ready_graduates_both_two_or_more_races_count': '2CRB',
        'college_ready_graduates_both_two_or_more_races_percent': '2CRB',
        # 'college_ready_graduates_both_white_count': 'WCRB',
        'college_ready_graduates_both_white_percent': 'WCRB',
        # 'college_ready_graduates_both_economically_disadvantaged_count': 'ECRB',
        'college_ready_graduates_both_economically_disadvantaged_percent': 'ECRB',
        # 'college_ready_graduates_both_limited_english_proficient_count': 'LCRB',
        'college_ready_graduates_both_limited_english_proficient_percent': 'LCRB',
        # 'college_ready_graduates_both_at_risk_count': 'RCRB',
        'college_ready_graduates_both_at_risk_percent': 'RCRB',
        'avg_sat_score_all_students': 'A0CSA',
        'avg_sat_score_african_american': 'B0CSA',
        'avg_sat_score_american_indian': 'I0CSA',
        'avg_sat_score_asian': '30CSA',
        'avg_sat_score_hispanic': 'H0CSA',
        'avg_sat_score_pacific_islander': '40CSA',
        'avg_sat_score_two_or_more_races': '20CSA',
        'avg_sat_score_white': 'W0CSA',
        'avg_sat_score_economically_disadvantaged': 'E0CSA',
        'avg_act_score_all_students': 'A0CAA',
        'avg_act_score_african_american': 'B0CAA',
        'avg_act_score_american_indian': 'I0CAA',
        'avg_act_score_asian': '30CAA',
        'avg_act_score_hispanic': 'H0CAA',
        'avg_act_score_pacific_islander': '40CAA',
        'avg_act_score_two_or_more_races': '20CAA',
        'avg_act_score_white': 'W0CAA',
        'avg_act_score_economically_disadvantaged': 'E0CAA',
        # 'ap_ib_all_students_count_above_criterion': 'A0BKA',
        'ap_ib_all_students_percent_above_criterion': 'A0BKA',
        # 'ap_ib_african_american_count_above_criterion': 'B0BKA',
        'ap_ib_african_american_percent_above_criterion': 'B0BKA',
        # 'ap_ib_asian_count_above_criterion': '30BKA',
        'ap_ib_asian_percent_above_criterion': '30BKA',
        # 'ap_ib_hispanic_count_above_criterion': 'H0BKA',
        'ap_ib_hispanic_percent_above_criterion': 'H0BKA',
        # 'ap_ib_american_indian_count_above_criterion': 'I0BKA',
        'ap_ib_american_indian_percent_above_criterion': 'I0BKA',
        # 'ap_ib_pacific_islander_count_above_criterion': '40BKA',
        'ap_ib_pacific_islander_percent_above_criterion': '40BKA',
        # 'ap_ib_two_or_more_races_count_above_criterion': '20BKA',
        'ap_ib_two_or_more_races_percent_above_criterion': '20BKA',
        # 'ap_ib_white_count_above_criterion': 'W0BKA',
        'ap_ib_white_percent_above_criterion': 'W0BKA',
        # 'ap_ib_economically_disadvantaged_count_above_criterion': 'E0BKA',
        'ap_ib_economically_disadvantaged_percent_above_criterion': 'E0BKA',
        'ap_ib_all_students_percent_taking': 'A0BTA',
        'ap_ib_african_american_percent_taking': 'B0BTA',
        'ap_ib_asian_percent_taking': '30BTA',
        'ap_ib_hispanic_percent_taking': 'H0BTA',
        'ap_ib_american_indian_percent_taking': 'I0BTA',
        'ap_ib_pacific_islander_percent_taking': '40BTA',
        'ap_ib_two_or_more_races_percent_taking': '20BTA',
        'ap_ib_white_percent_taking': 'W0BTA',
        'ap_ib_economically_disadvantaged_percent_taking': 'E0BTA',
        # 'dropout_all_students_count': 'A0912DR',
        'dropout_all_students_percent': 'A0912DR',
        # 'dropout_african_american_count': 'B0912DR',
        'dropout_african_american_percent': 'B0912DR',
        # 'dropout_asian_count': '30912DR',
        'dropout_asian_percent': '30912DR',
        # 'dropout_hispanic_count': 'H0912DR',
        'dropout_hispanic_percent': 'H0912DR',
        # 'dropout_american_indian_count': 'I0912DR',
        'dropout_american_indian_percent': 'I0912DR',
        # 'dropout_pacific_islander_count': '40912DR',
        'dropout_pacific_islander_percent': '40912DR',
        # 'dropout_two_or_more_races_count': '20912DR',
        'dropout_two_or_more_races_percent': '20912DR',
        # 'dropout_white_count': 'W0912DR',
        'dropout_white_percent': 'W0912DR',
        # 'dropout_at_risk_count': 'R0912DR',
        'dropout_at_risk_percent': 'R0912DR',
        # 'dropout_economically_disadvantaged_count': 'E0912DR',
        'dropout_economically_disadvantaged_percent': 'E0912DR',
        # 'dropout_limited_english_proficient_count': 'E0912DR',
        'dropout_limited_english_proficient_percent': 'E0912DR',
        # 'four_year_graduate_all_students_count': 'AGC4X',
        'four_year_graduate_all_students_percent': 'AGC4X',
        # 'four_year_graduate_african_american_count': 'BGC4X',
        'four_year_graduate_african_american_percent': 'BGC4X',
        # 'four_year_graduate_american_indian_count': 'IGC4X',
        'four_year_graduate_american_indian_percent': 'IGC4X',
        # 'four_year_graduate_asian_count': '3GC4X',
        'four_year_graduate_asian_percent': '3GC4X',
        # 'four_year_graduate_hispanic_count': 'HGC4X',
        'four_year_graduate_hispanic_percent': 'HGC4X',
        # 'four_year_graduate_pacific_islander_count': '4GC4X',
        'four_year_graduate_pacific_islander_percent': '4GC4X',
        # 'four_year_graduate_two_or_more_races_count': '2GC4X',
        'four_year_graduate_two_or_more_races_percent': '2GC4X',
        # 'four_year_graduate_white_count': 'WGC4X',
        'four_year_graduate_white_percent': 'WGC4X',
        # 'four_year_graduate_at_risk_count': 'RGC4X',
        'four_year_graduate_at_risk_percent': 'RGC4X',
        # 'four_year_graduate_economically_disadvantaged_count': 'EGC4X',
        'four_year_graduate_economically_disadvantaged_percent': 'EGC4X',
        # 'four_year_graduate_limited_english_proficient_count': 'L3C4X',
        'four_year_graduate_limited_english_proficient_percent': 'L3C4X',
        'attendance_rate': 'A0AT',
    },
    'reference': {
        'accountability_rating': '_RATING',
    },
}
