# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0004_auto_20151214_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstats',
            name='college_ready_graduates_math_pacific_islander_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent of college ready Pacific Islander graduates in math'),
        ),
    ]
