# Generated by Django 3.1.12 on 2022-01-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0009_auto_20210208_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtstats',
            name='teacher_avg_20_plus_year_salary',
        ),
        migrations.AddField(
            model_name='districtstats',
            name='teacher_avg_21_to_30_year_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Average salary for teachers with 21-30 years experience'),
        ),
        migrations.AddField(
            model_name='districtstats',
            name='teacher_avg_30_plus_year_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Average salary for teachers with over 30 years experience'),
        ),
    ]
