# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0041_auto_20151125_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='charter',
            field=models.BooleanField(default=False),
        ),
    ]
