# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0042_district_charter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='charter',
            field=models.BooleanField(default=False, verbose_name='Charter status'),
        ),
    ]
