# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20151109_0319'),
        ('states', '0004_auto_20170216_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCohorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, verbose_name='Gender')),
                ('ethnicity', models.CharField(blank=True, choices=[('White', 'White'), ('Hispanic', 'Hispanic'), ('African American', 'African American'), ('Others', 'Others')], max_length=30, verbose_name='Ethnicity')),
                ('economic_status', models.CharField(blank=True, choices=[('Economically Disadvantaged', 'Economically Disadvantaged'), ('Not Economically Disadvantaged', 'Not Economically Disadvantaged')], max_length=30, verbose_name='Economic status')),
                ('enrolled_8th', models.IntegerField(null=True)),
                ('enrolled_9th', models.IntegerField(null=True)),
                ('enrolled_9th_percent', models.FloatField(null=True)),
                ('enrolled_10th', models.IntegerField(null=True)),
                ('enrolled_10th_percent', models.FloatField(null=True)),
                ('lessthan_10th_enrolled', models.IntegerField(null=True)),
                ('lessthan_10th_enrolled_percent', models.FloatField(null=True)),
                ('graduated', models.IntegerField(null=True)),
                ('graduated_percent', models.FloatField(null=True)),
                ('enrolled_4yr', models.IntegerField(null=True)),
                ('enrolled_4yr_percent', models.FloatField(null=True)),
                ('enrolled_2yr', models.IntegerField(null=True)),
                ('enrolled_2yr_percent', models.FloatField(null=True)),
                ('enrolled_out_of_state', models.IntegerField(null=True)),
                ('enrolled_out_of_state_percent', models.IntegerField(null=True)),
                ('total_enrolled', models.IntegerField(null=True)),
                ('total_enrolled_percent', models.FloatField(null=True)),
                ('enrolled_wo_record', models.IntegerField(null=True)),
                ('enrolled_wo_record_percent', models.FloatField(null=True)),
                ('total_degrees', models.IntegerField(null=True)),
                ('total_degrees_percent', models.FloatField(null=True)),
                ('bacc', models.IntegerField(null=True)),
                ('bacc_acc', models.IntegerField(null=True)),
                ('bacc_cert', models.IntegerField(null=True)),
                ('assoc', models.IntegerField(null=True)),
                ('accoc_cert', models.IntegerField(null=True)),
                ('cert', models.IntegerField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='states.State')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cohorts', to='stats.SchoolYear')),
            ],
            options={
                'verbose_name_plural': 'State cohorts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='statecohorts',
            unique_together=set([('state', 'year', 'gender', 'ethnicity', 'economic_status')]),
        ),
    ]
