# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20170721_1629'),
        ('states', '0007_remove_statecohorts_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statecohorts',
            old_name='state_cohorts',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='statecohorts',
            old_name='cohorts_year',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='statecohorts',
            unique_together=set([('state', 'year')]),
        ),
    ]
