# Generated by Django 2.2.4 on 2019-08-08 22:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_auto_20170824_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Fax number of personnel'),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number of personnel'),
        ),
    ]
