# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_auto_20170725_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecohorts',
            name='ethnicity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statecohorts',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
