# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0015_auto_20170803_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecohorts',
            name='economic_status',
            field=models.CharField(blank=True, choices=[('Economically Disadvantaged', 'Economically Disadvantaged'), ('Not Economically Disadvantaged', 'Not Economically Disadvantaged')], default='', max_length=30, verbose_name='Economic status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecohorts',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Hispanic', 'Hispanic'), ('African American', 'African American'), ('Others', 'Others')], default='', max_length=30, verbose_name='Ethnicity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecohorts',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], default='', max_length=30, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
