# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_auto_20151211_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstats',
            name='teacher_total_fte_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of full time equivalent teachers'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='teacher_total_fte_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent of full time equivalent teachers'),
        ),
    ]
