# Generated by Django 2.1.7 on 2019-03-27 23:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0006_auto_20170216_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Fax number of personnel'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number of personnel'),
        ),
    ]
