# Generated by Django 2.2.4 on 2019-08-29 14:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0009_auto_20190808_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Fax number of personnel'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number of personnel'),
        ),
    ]
