# Generated by Django 3.1.4 on 2021-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0010_auto_20190829_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusstats',
            name='accountability_rating',
            field=models.CharField(blank=True, choices=[('M', 'Met standard'), ('A', 'Met alternative standard'), ('T', 'Met alternative standard'), ('I', 'Improvement required'), ('X', 'Not rated'), ('Z', 'Not rated'), ('Q', 'Not rated (data integrity issue)'), ('T', 'Not rated (Annexed)'), ('H', 'Not rated (Harvey provision)'), ('P', 'Not rated (Paired campus)'), ('DD', 'Not Rated: Declared State of Disaster'), ('', None)], default='', max_length=2, verbose_name='Accountability rating'),
        ),
        migrations.AlterField(
            model_name='campusstats',
            name='closing_the_gaps_rating',
            field=models.CharField(blank=True, choices=[('M', 'Met standard'), ('A', 'Met alternative standard'), ('T', 'Met alternative standard'), ('I', 'Improvement required'), ('X', 'Not rated'), ('Z', 'Not rated'), ('Q', 'Not rated (data integrity issue)'), ('T', 'Not rated (Annexed)'), ('H', 'Not rated (Harvey provision)'), ('P', 'Not rated (Paired campus)'), ('DD', 'Not Rated: Declared State of Disaster'), ('', None)], default='', max_length=2, verbose_name='Closing the gaps rating'),
        ),
        migrations.AlterField(
            model_name='campusstats',
            name='school_progress_rating',
            field=models.CharField(blank=True, choices=[('M', 'Met standard'), ('A', 'Met alternative standard'), ('T', 'Met alternative standard'), ('I', 'Improvement required'), ('X', 'Not rated'), ('Z', 'Not rated'), ('Q', 'Not rated (data integrity issue)'), ('T', 'Not rated (Annexed)'), ('H', 'Not rated (Harvey provision)'), ('P', 'Not rated (Paired campus)'), ('DD', 'Not Rated: Declared State of Disaster'), ('', None)], default='', max_length=2, verbose_name='School progress rating'),
        ),
        migrations.AlterField(
            model_name='campusstats',
            name='student_achievement_rating',
            field=models.CharField(blank=True, choices=[('M', 'Met standard'), ('A', 'Met alternative standard'), ('T', 'Met alternative standard'), ('I', 'Improvement required'), ('X', 'Not rated'), ('Z', 'Not rated'), ('Q', 'Not rated (data integrity issue)'), ('T', 'Not rated (Annexed)'), ('H', 'Not rated (Harvey provision)'), ('P', 'Not rated (Paired campus)'), ('DD', 'Not Rated: Declared State of Disaster'), ('', None)], default='', max_length=2, verbose_name='Student achievement rating'),
        ),
    ]
