# Generated by Django 3.1.12 on 2022-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0014_auto_20220308_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by students chronically absent over students in membership'),
        ),
    ]
