# Generated by Django 3.1.12 on 2022-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0015_campusstats_chronic_absenteeism_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusstats',
            old_name='chronic_absenteeism_rate',
            new_name='chronic_absenteeism_all_students_percent',
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_african_american_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by African American students chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_american_indian_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by American Indian students chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_asian_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by Asian students chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_hispanic_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by Hispanic students chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_pacific_islander_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by Pacific Islander students chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_two_or_more_races_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by students of two or more races chronically absent over students in membership'),
        ),
        migrations.AddField(
            model_name='campusstats',
            name='chronic_absenteeism_white_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by White students chronically absent over students in membership'),
        ),
    ]
