# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='states.State'),
        ),
        migrations.AlterUniqueTogether(
            name='regionstats',
            unique_together=set([('region', 'year')]),
        ),
    ]
