# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 20:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20170813_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Region shape'),
        ),
    ]
