# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20170721_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioncohorts',
            name='year',
        ),
    ]
