# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_auto_20170725_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncohorts',
            name='ethnicity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
