# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0011_auto_20170725_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncohorts',
            name='accoc_cert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='assoc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_acc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_cert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='cert',
            field=models.IntegerField(null=True),
        ),
    ]
