# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0012_auto_20170725_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncohorts',
            name='accoc_cert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='assoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_acc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_cert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='cert',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='economic_status',
            field=models.CharField(choices=[('Economically Disadvantaged', '1'), ('Not Economically Disadvantaged', '2')], max_length=1, null=True, verbose_name='Economic status'),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'white'), ('Hispanic', 'hispanic'), ('African American', 'african american'), ('Others', 'other')], max_length=16, null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
