# Generated by Django 3.1.12 on 2022-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0012_auto_20220120_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionstats',
            name='chronic_absenteeism_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Chronic absenteeism rate as calculated by students chronically absent over students in membership'),
        ),
    ]
