# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0013_auto_20170801_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncohorts',
            name='economic_status',
            field=models.CharField(choices=[('ED', 'Economically Disadvantaged'), ('NED', 'Not Economically Disadvantaged')], max_length=1, null=True, verbose_name='Economic status'),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='ethnicity',
            field=models.CharField(choices=[('W', 'White'), ('H', 'Hispanic'), ('B', 'African American'), ('O', 'Others')], max_length=16, null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
