# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20170721_1629'),
        ('regions', '0016_auto_20170802_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regioncohorts',
            unique_together=set([('region', 'year', 'gender', 'ethnicity', 'economic_status')]),
        ),
    ]
