# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0018_auto_20170803_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncohorts',
            name='accoc_cert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='assoc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_acc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='bacc_cert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='cert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_10th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_10th_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_2yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_2yr_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_4yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_4yr_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_8th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_9th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='enrolled_9th_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='graduated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='graduated_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='lessthan_10th_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='lessthan_10th_enrolled_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='total_degrees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='total_degrees_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='total_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regioncohorts',
            name='total_enrolled_percent',
            field=models.FloatField(null=True),
        ),
    ]
