# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='County name')),
                ('slug', models.SlugField()),
                ('fips', models.CharField(max_length=3, verbose_name='County FIPS place code')),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
    ]
