# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20170721_1629'),
        ('counties', '0002_county_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCohorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, verbose_name='Gender')),
                ('ethnicity', models.CharField(blank=True, choices=[('White', 'White'), ('Hispanic', 'Hispanic'), ('African American', 'African American'), ('Others', 'Others')], max_length=30, verbose_name='Ethnicity')),
                ('economic_status', models.CharField(blank=True, choices=[('Economically Disadvantaged', 'Economically Disadvantaged'), ('Not Economically Disadvantaged', 'Not Economically Disadvantaged')], max_length=30, verbose_name='Economic status')),
                ('enrolled_8th', models.IntegerField()),
                ('enrolled_9th', models.IntegerField()),
                ('enrolled_9th_percent', models.FloatField()),
                ('enrolled_10th', models.IntegerField()),
                ('enrolled_10th_percent', models.FloatField()),
                ('lessthan_10th_enrolled', models.IntegerField()),
                ('lessthan_10th_enrolled_percent', models.FloatField()),
                ('graduated', models.IntegerField()),
                ('graduated_percent', models.FloatField()),
                ('enrolled_4yr', models.IntegerField()),
                ('enrolled_4yr_percent', models.FloatField()),
                ('enrolled_2yr', models.IntegerField()),
                ('enrolled_2yr_percent', models.FloatField()),
                ('total_enrolled', models.IntegerField()),
                ('total_enrolled_percent', models.FloatField()),
                ('total_degrees', models.IntegerField()),
                ('total_degrees_percent', models.FloatField()),
                ('bacc', models.IntegerField(blank=True, null=True)),
                ('bacc_acc', models.IntegerField(blank=True, null=True)),
                ('bacc_cert', models.IntegerField(blank=True, null=True)),
                ('assoc', models.IntegerField(blank=True, null=True)),
                ('accoc_cert', models.IntegerField(blank=True, null=True)),
                ('cert', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='counties.County')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_cohorts', to='cohorts.CohortsYear')),
            ],
            options={
                'verbose_name_plural': 'County cohorts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='countycohorts',
            unique_together=set([('county', 'year', 'gender', 'ethnicity', 'economic_status')]),
        ),
    ]
