# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20170721_1629'),
        ('counties', '0003_auto_20170804_1803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countycohorts',
            unique_together=set([('county', 'year', 'economic_status')]),
        ),
    ]
