# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0005_county_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countycohorts',
            name='accoc_cert',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='assoc',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='bacc',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='bacc_acc',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='bacc_cert',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_10th_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_2yr_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_4yr_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_9th_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_out_of_state_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='enrolled_wo_record_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='graduated_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='lessthan_10th_enrolled_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='total_degrees_percent',
        ),
        migrations.RemoveField(
            model_name='countycohorts',
            name='total_enrolled_percent',
        ),
    ]
