# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0006_auto_20170808_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countycohorts',
            options={},
        ),
    ]
