# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0007_auto_20170810_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='countycohorts',
            name='enrolled_out_of_state',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countycohorts',
            name='enrolled_out_of_state_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countycohorts',
            name='enrolled_wo_record',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countycohorts',
            name='enrolled_wo_record_percent',
            field=models.FloatField(null=True),
        ),
    ]
