# Generated by Django 2.1.7 on 2019-03-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0007_auto_20170824_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='state_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='County State ID code'),
        ),
    ]
