# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_auto_20170721_1629'),
        ('counties', '0008_auto_20170810_2322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countycohorts',
            unique_together=set([('county', 'year', 'economic_status', 'gender', 'ethnicity')]),
        ),
    ]
