SCHEMA = {
    '8thGradeRegionGenderEthnicityEconFY06': {
        'gender': 'Gender',
        'ethnicity': 'Ethnicity',
        'economic_status': 'Economic Status',
        'enrolled_8th': '8th Grade (FY 2006)',
        'enrolled_9th': 'Enrolled in 9th Grade (FY 2007)',
        'enrolled_9th_percent': '% Enrolled in 9th Grade (FY 2007)',
        'enrolled_10th': 'Enrolled in 10th Grade(FY 2008)',
        'enrolled_10th_percent': '% Enrolled in 10th Grade (FY 2008)',
        'lessthan_10th_enrolled': 'Enrolled in <10th Grade (FY 2008)',
        'lessthan_10th_enrolled_percent': '% Enrolled in <10th Grade (FY 2008)',
        'graduated': 'High School Graduate FY 2009-2011',
        'graduated_percent': '% High School Graduate FY 2009-2011',
        'enrolled_4yr': 'Enrolled TX 4-year',
        'enrolled_4yr_percent': '% Enrolled TX 4-year',
        'enrolled_2yr': 'Enrolled TX 2-year',
        'enrolled_2yr_percent': '% Enrolled TX 2-year',
        'total_enrolled': 'Enrolled in Higher Education',
        'total_enrolled_percent': '% Enrolled in Higher Education',
        # '': 'No Public HS Grad Record Enrolled in Higher Ed',
        # '': '% No Public HS Grad Record Enrolled in Higher Ed',
        'total_degrees': 'Higher Ed Degree or Certificate Texas',
        'total_degrees_percent': '% Higher Ed Degree or Certificate Texas'
    },
    'RegionCountyEconFY06': {
        # 'gender': 'Gender',
        # 'ethnicity': 'Ethnicity',
        'economic_status': 'Economic Status',
        'enrolled_8th': '8th Grade (FY 2006)',
        'enrolled_9th': 'Enrolled in 9th Grade (FY 2007)',
        'enrolled_9th_percent': '% Enrolled in 9th Grade (FY 2007)',
        'enrolled_10th': 'Enrolled in 10th Grade(FY 2008)',
        'enrolled_10th_percent': '% Enrolled in 10th Grade (FY 2008)',
        'lessthan_10th_enrolled': 'Enrolled in <10th Grade (FY 2008)',
        'lessthan_10th_enrolled_percent': '% Enrolled in <10th Grade (FY 2008)',
        'graduated': 'High School Graduate FY 2009-2011',
        'graduated_percent': '% High School Graduate FY 2009-2011',
        'enrolled_4yr': 'Enrolled TX 4-year',
        'enrolled_4yr_percent': '% Enrolled TX 4-year',
        'enrolled_2yr': 'Enrolled TX 2-year',
        'enrolled_2yr_percent': '% Enrolled TX 2-year',
        'total_enrolled': 'Enrolled in Higher Education',
        'total_enrolled_percent': '% Enrolled in Higher Education',
        # '': 'No Public HS Grad Record Enrolled in Higher Ed',
        # '': '% No Public HS Grad Record Enrolled in Higher Ed',
        'total_degrees': 'Higher Ed Degree or Certificate Texas',
        'total_degrees_percent': '% Higher Ed Degree or Certificate Texas'
    },
    'RegionCountyGenderFY06': {
        'gender': 'Gender',
        # 'ethnicity': 'Ethnicity',
        # 'economic_status': 'Economic Status',
        'enrolled_8th': '8th Grade (FY 2006)',
        'enrolled_9th': 'Enrolled in 9th Grade (FY 2007)',
        'enrolled_9th_percent': '% Enrolled in 9th Grade (FY 2007)',
        'enrolled_10th': 'Enrolled in 10th Grade(FY 2008)',
        'enrolled_10th_percent': '% Enrolled in 10th Grade (FY 2008)',
        'lessthan_10th_enrolled': 'Enrolled in <10th Grade (FY 2008)',
        'lessthan_10th_enrolled_percent': '% Enrolled in <10th Grade (FY 2008)',
        'graduated': 'High School Graduate FY 2009-2011',
        'graduated_percent': '% High School Graduate FY 2009-2011',
        'enrolled_4yr': 'Enrolled TX 4-year',
        'enrolled_4yr_percent': '% Enrolled TX 4-year',
        'enrolled_2yr': 'Enrolled TX 2-year',
        'enrolled_2yr_percent': '% Enrolled TX 2-year',
        'total_enrolled': 'Enrolled in Higher Education',
        'total_enrolled_percent': '% Enrolled in Higher Education',
        # '': 'No Public HS Grad Record Enrolled in Higher Ed',
        # '': '% No Public HS Grad Record Enrolled in Higher Ed',
        'total_degrees': 'Higher Ed Degree or Certificate Texas',
        'total_degrees_percent': '% Higher Ed Degree or Certificate Texas'
    }
}
